### PR TITLE
chore: reduce features

### PR DESCRIPTION
**Pull request by chris13524**
Did a quick pass and removed as many features as I could. Everything still seems to work and CI passes so...

Fixes RES-112

### CODE REVIEW

**Comment by jakubuid** [comment]
This should be merged only when we verify that it doesn't break bindings

**Comment by chris13524** [comment]
> This should be merged only when we verify that it doesn't break bindings

How do you think we should do that?

**Comment by jakubuid** [comment]
> How do you think we should do that?
We should do that locally per platform or test releases

**Review by jakubuid — APPROVED** [review]
Tested and LGTM 🙌

**Pull request merged**
